language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
addons:
  apt:
    packages:
    - libgraph-easy-perl
cache:
  directories:
  - $HOME/.cache
install:
- pip install docutils
script:
- python lddot $(which python) > python.dot
- cat python.dot
- graph-easy --as boxart < python.dot
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
