language: python
python:
- "3.2"
- "3.3"
- "3.4"
- pypy3
before_install:
- sudo apt-get update
- sudo apt-get install libgraph-easy-perl
install:
- pip install docutils
script:
- python lddot $(which python) > python.dot
- cat python.dot
- graph-easy --as boxart < python.dot
- find -name "*.rst" -print -exec rst2pseudoxml.py --strict {} /dev/null ";"

# vim:ts=2 sts=2 sw=2 et
