language: python
python:
- "3.2"
- "3.3"
- "3.4"
before_install:
- sudo apt-get update
- sudo apt-get install libgraph-easy-perl
script:
- python lddot $(which python) > python.dot
- cat python.dot
- graph-easy --as boxart < python.dot

# vim:ts=2 sts=2 sw=2 et
