dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- pypy
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
addons:
  apt:
    packages:
    - libgraph-easy-perl
install:
- pip install pydiatra pyflakes
- pip install docutils
- \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] || pip install pygments
script:
- python lddot $(which python) > python.dot
- cat python.dot
- graph-easy --as boxart < python.dot
- python -m pydiatra .
- pyflakes .
- \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] || private/check-rst

# vim:ts=2 sts=2 sw=2 et
