language: python
python:
- "3.2"
- "3.3"
- "3.4"
- pypy3
addons:
  apt:
    packages:
    - cpanminus
cache:
  directories:
  - $HOME/.cache
  - $HOME/perl5
install:
- export PERL5LIB="$HOME/perl5/lib/perl5"
- perl -MGraph::Easy -e '' || cpanm Graph::Easy
- pip install docutils
script:
- python lddot $(which python) > python.dot
- cat python.dot
- export PATH="$PATH:$HOME/perl5/bin"
- graph-easy --as boxart < python.dot
- find -name "*.rst" | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
