dist: trusty
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
addons:
  apt:
    packages:
    - libgraph-easy-perl
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
install:
- pip install pydiatra $pyflakes
- $if_pygments pip install docutils pygments
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- ./lddot $(which python) > python.dot
- cat python.dot
- graph-easy --as boxart < python.dot
- python -m pydiatra .
- pyflakes .
- $if_pygments private/check-rst

# vim:ts=2 sts=2 sw=2 et
