.\" Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
.\" SPDX-License-Identifier: MIT

.TH LDDOT 1 2019-03-11 "lddot 0.2" ""
.SH NAME
lddot \- print ELF dependencies in Graphviz format
.SH SYNOPSIS
.SY lddot
.I BINARY
.YS
.SH DESCRIPTION
.B lddot
prints ELF shared library dependencies of the binary in Graphviz format.
.SS Security
.B lddot
uses
.BR ldd (1)
under the hood,
and therefore might not be secure when used on untrusted input.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit.
.TP
.B \-\-version
Show version information and exit.
.SH EXAMPLE
.EX
$ \fBlddot $(command \-v bash) | graph\-easy \-\-as ascii\fP

                    +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
                    |                                                    |
                    |                                                    |
  +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+                       |
  |                 |                            v                       v
+\-\-\-\-\-\-\-\-\-\-\-+     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| /bin/bash | \-\-> | /lib/libncurses.so.5 | \-\-> | /lib/libdl.so.2 | \-\-> | /lib/libc.so.6 | \-\-> | ld\-linux.so.2 |
+\-\-\-\-\-\-\-\-\-\-\-+     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
  |                                              |                       ^                      ^
  +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+                      |
                                                 |                                              |
                                                 |                                              |
                                                 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
.EE
.SH SEE ALSO
.BR graphviz (7),
.BR ldd (1),
.BR readelf (1),
.BR lddtree (1)
