name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11-dev'
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: install deps
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
        sudo apt-get install graphviz libgraph-easy-perl
    - name: run tests
      run:
        make test network=1
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: check whether the executable was installed correctly
      run: |
        cd /
        lddot --version
        lddot --help
    - name: check whether the man page was installed correctly
      env:
        MANPATH: /home/runner/.local/share/man
        MANWIDTH: 80
      run: |
        cd /
        man 1 lddot | grep -A 10 -w LDDOT
    - name: run post-install tests
      run:
        make test-installed
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint lddot
    - name: check docs
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 doc/README

# vim:ts=2 sts=2 sw=2 et
