name: CI
on:
- push
- pull_request
jobs:

  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python: '3.8'
          os: ubuntu-22.04
        - python: '3.9'
          os: ubuntu-22.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
        - python: '3.13'
          os: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install deps
      run: |
        sudo apt-get install graphviz libgraph-easy-perl
    - name: run tests
      run:
        make test network=1
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: check whether the executable was installed correctly
      run: |
        cd /
        lddot --version
        lddot --help
    - name: check whether the man page was installed correctly
      env:
        MANPATH: /home/runner/.local/share/man
        MANWIDTH: 80
      run: |
        cd /
        man 1 lddot | grep -A 10 -w LDDOT
    - name: run post-install tests
      run: |
        rm lddot
        make test-installed
        git restore lddot
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint lddot
    - name: check docs
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 doc/README

  nonpython:
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install deps
      run: |
        sudo apt-get install mandoc
    - name: check docs
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
        mandoc -T lint doc/*.1

# vim:ts=2 sts=2 sw=2 et
